"""Reusable helpers for approximate MPC imitation examples."""

from .dagger import dagger_schedule, parse_float_tuple, parse_int_tuple
from .code_export import (
    CodeExportOptions,
    DenseLayerSpec,
    MLPExportSpec,
    QuantizationConfig,
    QuantizedDenseLayerSpec,
    QuantizedMLPExportSpec,
    TestCases,
    export_checkpoint,
    export_mlp_policy,
    load_mlp_checkpoint,
    make_random_test_cases,
    make_test_cases,
    quantize_mlp_policy,
)
from .dataset import (
    append_dataset,
    dataset_keep_per_step,
    estimate_dataset_gb,
    subsample_dataset_increment,
)
from .filters import (
    CompositeFilter,
    CostPercentileConfig,
    CostThresholdFilter,
    FilterBounds,
    StateBoundsFilter,
    StatePercentileConfig,
    calibrate_filter_bounds,
    filter_transition_valid_mask_host,
    filtered_rollout_valid_mask_host,
    infinite_filter_bounds,
    load_filter_bounds_npz,
    trajectory_finiteness,
    valid_state_jax,
)
from .metrics import (
    device_tree_block,
    format_filtered_rollout_plot_stats,
    format_rollout_metrics,
    quadratic_rollout_cost_host,
    rollout_qp_metrics,
    summarize_rollout_host,
)
from .models import MLP
from .noise import (
    sample_scaled_gaussian_noise,
    sample_scaled_unit_ball_noise,
    sample_scaled_unit_ball_noise_np,
    sample_unit_ball,
    sample_unit_ball_np,
)
from .normalization import (
    Normalization,
    apply_normalized_policy,
    compute_normalization,
    denormalize_targets,
    initial_normalization,
    normalize_inputs,
    normalize_targets,
)
from .outputs import (
    ACTION_SEQUENCE,
    FIRST_ACTION,
    PRIMAL_SOLUTION,
    OutputSpec,
    first_action_from_prediction,
    make_output_spec,
    prediction_target_name,
    select_prediction_target,
)
from .plotting import (
    plot_rollout_histogram_pair,
    plot_rollout_histograms,
    plot_state_distribution,
    plot_state_distribution_pair,
    state_plot_valid_mask,
)
from .rollouts import (
    PolicyRolloutOutput,
    SQPRolloutOutput,
    make_policy_rollout,
    make_sqp_collect_rollout,
)
from .serialization import jsonable, save_dataset_increment, save_flax_checkpoint, write_json
from .training import TrainingConfig, create_train_state, make_training_kernels, train_supervised_policy

__all__ = [
    "ACTION_SEQUENCE",
    "CompositeFilter",
    "CostPercentileConfig",
    "CostThresholdFilter",
    "CodeExportOptions",
    "DenseLayerSpec",
    "FIRST_ACTION",
    "FilterBounds",
    "MLP",
    "MLPExportSpec",
    "Normalization",
    "OutputSpec",
    "PRIMAL_SOLUTION",
    "PolicyRolloutOutput",
    "QuantizationConfig",
    "QuantizedDenseLayerSpec",
    "QuantizedMLPExportSpec",
    "SQPRolloutOutput",
    "StateBoundsFilter",
    "StatePercentileConfig",
    "TestCases",
    "TrainingConfig",
    "append_dataset",
    "apply_normalized_policy",
    "calibrate_filter_bounds",
    "compute_normalization",
    "create_train_state",
    "dagger_schedule",
    "dataset_keep_per_step",
    "denormalize_targets",
    "device_tree_block",
    "estimate_dataset_gb",
    "export_checkpoint",
    "export_mlp_policy",
    "filter_transition_valid_mask_host",
    "filtered_rollout_valid_mask_host",
    "first_action_from_prediction",
    "format_filtered_rollout_plot_stats",
    "format_rollout_metrics",
    "infinite_filter_bounds",
    "initial_normalization",
    "jsonable",
    "load_filter_bounds_npz",
    "load_mlp_checkpoint",
    "make_output_spec",
    "make_policy_rollout",
    "make_random_test_cases",
    "make_test_cases",
    "make_sqp_collect_rollout",
    "make_training_kernels",
    "normalize_inputs",
    "normalize_targets",
    "parse_float_tuple",
    "parse_int_tuple",
    "plot_rollout_histogram_pair",
    "plot_rollout_histograms",
    "plot_state_distribution",
    "plot_state_distribution_pair",
    "prediction_target_name",
    "quantize_mlp_policy",
    "quadratic_rollout_cost_host",
    "rollout_qp_metrics",
    "sample_scaled_gaussian_noise",
    "sample_scaled_unit_ball_noise",
    "sample_scaled_unit_ball_noise_np",
    "sample_unit_ball",
    "sample_unit_ball_np",
    "save_dataset_increment",
    "save_flax_checkpoint",
    "select_prediction_target",
    "state_plot_valid_mask",
    "subsample_dataset_increment",
    "summarize_rollout_host",
    "train_supervised_policy",
    "trajectory_finiteness",
    "valid_state_jax",
    "write_json",
]
