# Out-of-tree Crazyflie app for the AMPC neural controller.

CRAZYFLIE_BASE := $(CURDIR)/../crazyflie-firmware
OOT := $(CURDIR)
OOT_CONFIG := $(OOT)/app-config

include $(CRAZYFLIE_BASE)/tools/make/oot.mk
